/*Marco Antônio da Silva Leite - Sistemas de  Controle  de Acervo  Bilbliográfico*/

CREATE TABLE USUARIO(
COD_USUARIO BIGINT NOT NULL PRIMARY KEY,
NOME_USUARIO VARCHAR(50) NOT NULL,
TELEFONE_USUARIO INTEGER NOT NULL,
RG_USUARIO INTEGER NOT NULL,
ENDERECO_USUARIO VARCHAR(70) NOT NULL  
);

CREATE TABLE EDITORA(
COD_EDITORA BIGINT NOT NULL PRIMARY KEY,
NOME_EDITORA VARCHAR(30) NOT NULL,
ENDERECO_EDITORA VARCHAR(70) NOT NULL,
CONTATO_EDITORA INTEGER NOT NULL
);

CREATE TABLE AUTOR(
COD_AUTOR BIGINT NOT NULL PRIMARY KEY,
NOME_AUTOR VARCHAR(50) NOT NULL,
NASCIONALIDADE_AUTOR VARCHAR(30) NOT NULL
);

CREATE TABLE LIVRO(
COD_LIVRO BIGINT NOT NULL PRIMARY KEY,
COD_EDITORA BIGINT NOT NULL,
TITULO_LIVRO VARCHAR(50) NOT NULL,
TITULO_ORIGINAL VARCHAR(50) NOT NULL,
SITUACAO_LIVRO CHAR(2) NOT NULL,
FOREIGN KEY(COD_EDITORA) REFERENCES EDITORA   
);

CREATE TABLE RESERVA(
COD_RES_EMPRESTIMO BIGINT PRIMARY KEY,
COD_USUARIO BIGINT NOT NULL,
COD_LIVRO BIGINT NOT NULL,
DT_HR_RESERVA DATE NOT NULL,
RES_DT_HR_EMPRESTIMO DATE NOT NULL,
DT_HR_DEVOLUCAO DATE NOT NULL,
VALOR_MULTA NUMERIC(5,2) NOT NULL,
FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO,
FOREIGN KEY (COD_LIVRO) REFERENCES LIVRO  
);

CREATE TABLE CATEGORIA_LIVRO(
COD_CATEGORIA BIGINT NOT NULL PRIMARY KEY,
DESC_CATEGORIA VARCHAR(100) NOT NULL,
NOME_CATEGORIA VARCHAR(30)
);

CREATE TABLE ESCREVE (
COD_LIVRO BIGINT NOT NULL,
COD_AUTOR BIGINT NOT NULL,
FOREIGN KEY (COD_AUTOR) REFERENCES AUTOR,
FOREIGN KEY (COD_LIVRO)  REFERENCES LIVRO  
);

CREATE TABLE SELECIONA(
COD_LIVRO BIGINT NOT NULL,
COD_CATEGORIA BIGINT NOT NULL,
FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA_LIVRO,
FOREIGN KEY (COD_LIVRO) REFERENCES LIVRO  
);

